### ISSUE TITLE
Incorrect information on divs inside description lists.

### ISSUE THREAD

**Issue by dtrower** [joyheron/responsible-web-apps#2]
Back in 2016, WHATWG added to the [HTML spec](https://github.com/whatwg/html/commit/5454d702e0262749aba55576dda32c48e0e498f0) the ability to include `<div>` elements inside of `<dl>` elements and later was ported by W3C into the [HTML 5.2 Recommendation](https://www.w3.org/TR/html52/grouping-content.html#the-dl-element).  As a result, the following markup is now allowed in HTML:

```HTML
<dl>
    <div>
        <dt><cite>FBI</cite></dt>
        <dd><cite>FBI</cite>, a crime drama television program, centers around the inner workings of the New York field office of the FBI as they work major cases involving terrorism, kidnapping, organized crime, and counterintelligence.</dd>
    </div>
    <div>
        <dt><cite>Criminal Minds</cite></dt>
        <dd><cite>Criminal Minds</cite>, a police&#8211;procedural television program, follows profilers of the Behavioral Analysis Unit of the FBI as they profile the criminal unsub or &#8220;unknown subject&#8221;).</dd>
    </div>
    <div>
        <dt><cite>Bones</cite></dt>
        <dd><cite>Bones</cite>, a crime comedy&#8211;drama, features the joint efforts of FBI Special Agent Seeley Booth and forensic anthropologist Dr. Temperance &#8220;Bones&#8221; Brennan as they solve FBI crimes concerning human remains.  The characters use forensic anthropology and forensic archaeology in the course of solving the crimes.</dd>
    </div>
</dl>
```

**Comment by joyheron** [comment]
Hi! Thanks for the information. I'd like to update the information on my site.
Do you know what the compatibility of the change is? It might be that I remembered that incorrectly because I was having to support an old browser.

**Comment by joyheron** [comment]
I've updated the text to read:

_Update:_ Originally, I discussed having difficulties styling description lists.
This statement is no longer correct for modern browsers which implement the <a href="https://www.w3.org/TR/html52/grouping-content.html#the-dl-element">HTML 5.2 Recommendation</a>
because they now allow a <code>div</code> as a wrapper around the <code>dt</code> and <code>dd</code> elements.


I hope that is more correct.

**Comment by dtrower** [comment]
@joyheron, I did some testing of some code identical to what I had posted in the original post (with CSS styling) on versions of IE 7-10 on the different versions of Windows that run those versions.   Overall things displayed and functioned as intended with the description lists with the `<div>` element wrapping the pairs of `<dt>` and `<dd>` elements.  The one exception was a slight display issue on one of the `<dt>` elements in IE 7 on Windows XP.  While the use of `<div>` elements wrapping the pairs of `<dt>` and `<dd>` elements is non-conforming of the standards under HTML4, 5, and 5.1, it appears that browser manufactures were more forgiving than the standards on this.  That's not to say that there isn't a compatibility in an old browser somewhere that I didn't see or test though.

I think your statement is fine.  However, I typically would recommend in documents like this that rather than outright removing your previous statement, you would be better suited by using the `<del>` element to mark the previous content as having been deleted from the original document and marking this new paragraph with `<ins>`.  Particularly since you are indicating this statement as being an update and referencing what you originally had.  You can then use CSS styling to control exactly how the deleted and inserted text appears visually in the browser.  There are some accessibility concerns related to `<del>` and `<ins>` that might need to be explored and a solution implemented so users using screen readers will hear that the one paragraph has been deleted while the other paragraph was inserted. [[1]](https://adrianroselli.com/2017/12/tweaking-text-level-styles.html) [[2]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ins) [[3]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del) [[4]](https://stackoverflow.com/questions/61623020/jaws-not-able-to-read-ins-del-elements-with-before-and-after-pseudo-elements)

I'll create a pull request that reverts 39d63 and then marks up the deleted paragraph with `<del>` and re-adds the new paragraph using the `<ins>` elements with the original datetime that you made the change.  It will also have some CSS to better style the deletion and inserted text.

**Comment by joyheron** [comment]
Thanks again for all of your help on this and for doing the testing in older browsers.

I may tweak the text in the future -- if older browsers are lenient with the extra `<div>` elements, there should be even less reason for concern about using description lists. But I will close this issue for now.
