### ISSUE TITLE
Grid Area assignment, mobile example

### ISSUE THREAD

**Issue by SNlsn** [joyheron/responsible-web-apps#5]
"CSS for mobile devices" section
https://responsibleweb.app/#CSS-Grid-with-Breakpoints

Did you intentionally assign the two asides to the "header" grid area in your code example?

BTW, thanks for developing responsibleweb.app - it's very helpful material

**Comment by joyheron** [comment]
Thanks so much for bringing this to my attention!
This is fixed now.

**Comment by SNlsn** [comment]
Oh, good. I stared at it for a long time and I hesitated to write because I was afraid it was me not understanding Grid Areas. :) Thank you again for this helpful resource.
