### ISSUE TITLE
Verbosity doesn't necessarily make for good image alt text

### ISSUE THREAD

**Issue by thewildmage** [joyheron/responsible-web-apps#8]
The ["Descriptive alt text for images"](https://responsibleweb.app/#Image-Alt) section mentions that:

> ...we should be verbose: we should use the alt to describe the picture visually for those users who cannot see it.

This statement actually seems to run counter to advice I've seen about alt texts in another article, ["Alt-Texts: The Ultimate Guide"](https://axesslab.com/alt-texts/), which says (among lots of other super helpful tips) that:

> [A sighted user viewing an image] can also get the necessary information from the image at a glance, and that’s what we’re trying to achieve for users with screen readers as well. Give the necessary information in the alt-text, but make it as short and concise as possible.

**Comment by joyheron** [comment]
Hi! Thanks for getting pointing this problem out. 

I've updated the section about alt-texts in my article and also linked to that great article that you mentioned.

The new version is here: https://responsibleweb.app/#Image-Alt

**Comment by thewildmage** [comment]
Awesome! Looks great to me. Thanks for listening and thanks for the very helpful website!
